# include: package:flutter_lints/flutter.yaml
include: package:very_good_analysis/analysis_options.7.0.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:

  rules:
    public_member_api_docs: false
    