name: nodelabs_case_study
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  animated_text_kit: ^4.2.3
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  country_flags: ^3.2.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  envied: ^1.0.0
  firebase_analytics: ^11.6.0
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_inner_shadow: ^0.0.1
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  lottie: ^3.3.1
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  very_good_analysis: ^7.0.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/euclid-circular-a/Euclid Circular A Light.ttf
          weight: 300
        - asset: assets/fonts/euclid-circular-a/Euclid Circular A Regular.ttf
          weight: 400
        - asset: assets/fonts/euclid-circular-a/Euclid Circular A Medium.ttf
          weight: 500
        - asset: assets/fonts/euclid-circular-a/Euclid Circular A SemiBold.ttf
          weight: 600
        - asset: assets/fonts/euclid-circular-a/Euclid Circular A Bold.ttf
          weight: 700
          
  uses-material-design: true

  assets:
    - assets/env/  
    - assets/images/
    - assets/translations/
    - assets/lottie/

targets:
  $default:
    builders:
      envied_generator|envied:
        options:
          path: .env.custom
          override: true 

flutter_native_splash:
  background_image: "assets/images/splash.png"